### ISSUE TITLE
migration vrf library from r2ishiguro to curve25519-voi

### ISSUE THREAD

**Issue by zemyblue** [Finschia/ostracon#653]
## Summary

We replace the Ostracon's vrf library from r2ishiguro to curve25519-voi by #620 and #633. But this change has a consensus breaking change, So this Ostracon need to add the migration logic from r2ishiguro to curve25519-voi

## Problem Definition

The r2ishiguro vrf library was removed by #633. We still need it to verify a previous blocks. 

## Proposal

* Need to add r2ishiguro vrf library again. 
* Need to add a migration algorithm (r2ishiguro -> curve25519-voi) 
* Need to add the feature to prevent to reuse r2ishiguro after migrating to curve25519-voi.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by 0Tech** [comment]
#652 addresses the issue. Here is a brief description:

- Need to add r2ishiguro vrf library again.
  - Import the legacy logic into crypto/ed25519/internal/r2ishiguro, which hides the implementation from the other packages.
- Need to add a migration algorithm (r2ishiguro -> curve25519-voi)
  - Allow the new ostracon to verify the old r2ishiguro proofs.
  - Generation of the proof (by `VRFProve()`) always done by the new implementation, curve25519-voi.
- Need to add the feature to prevent to reuse r2ishiguro after migrating to curve25519-voi.
  - Introduce "versioned vrf" global instance, which manages its own version.
  - The version would be updated if it encounters a new valid proof.
  - Implementation with old version CANNOT be used.
