### ISSUE TITLE
Update golang version to 1.20

### ISSUE THREAD

**Issue by 0Tech** [Finschia/ostracon#664]
## Summary

We should stop using deprecated golang version 1.18 and update the minimum required golang version to 1.19 or later.

Refer: Finschia/finschia#228

## Problem Definition

We should use the maintained versions of golang to get updated with various patches, including security patches.

## Proposal

Change the minimum required golang version to 1.20, and update the relevant configs & logics.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ulbqb** [comment]
Would you try `make proto-gen`? I think it doesn't work in go 1.20.
